name: Test
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Factor
        run: |
          mkdir -p ~/opt
          cd ~/opt
          wget -q -O - https://downloads.factorcode.org/releases/0.98/factor-linux-x86-64-0.98.tar.gz | tar xzf -
      - name: Run Tests
        run: |
          PATH=~/opt/factor:$PATH python3 test/run-tests.py -v
